# Generated by Django 5.1.4 on 2025-01-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_content_days_entry_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='entry_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
